version: '3'

services:
  ql:
    image: whyour/qinglong:latest  
    restart: always
    ports:
      - "5700:5700"  
    volumes:        
      - ql-web:/ql    
    container_name: ql_new    
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
volumes:
  ql-web:
