version: '3'

services:
  ql:
    image: whyour/qinglong:latest  
    restart: always
    ports:
      - "5700:5700"  
    volumes:        
      - ql-web:/ql/config       
      - ql-web:/ql/log        
      - ql-web:/ql/db             
      - ql-web:/ql/scripts
      - ql-web:/ql/repo   
    container_name: ql_new    
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
      
volumes:
  ql-web:
